targets:
  $default:
    sources:
      - lib/**
    builders:
      json_serializable:
        options:
          include_if_null: false
      artemis:
        options:
          custom_parser_import: lib/time_parser.dart
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
              use_custom_parser: true
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/account.graphql
              output: lib/dart/account.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/authentication.graphql
              output: lib/dart/authentication.graphql.dart            
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/board-card.graphql
              output  : lib/dart/board-card.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/board-list.graphql
              output: lib/dart/board-list.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/board.graphql
              output: lib/dart/board.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/comment.graphql
              output: lib/dart/comment.graphql.dart            
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/company.graphql
              output: lib/dart/company.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/point-of-sale.graphql
              output: lib/dart/point-of-sale.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/tickets.graphql
              output: lib/dart/tickets.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/user.graphql
              output: lib/dart/user.graphql.dart            
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/country.graphql
              output: lib/dart/country.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/notes.graphql
              output: lib/dart/notes.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/project.graphql
              output: lib/dart/project.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/brand.graphql
              output: lib/dart/brand.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/catalogue-category.graphql
              output: lib/dart/catalogue-category.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/internal-product.graphql
              output: lib/dart/internal-product.graphql.dart            
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/contact.graphql
              output: lib/dart/contact.graphql.dart            
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/quotation.graphql
              output: lib/dart/quotation.graphql.dart